CREATE TABLE IF NOT EXISTS DW_RAW.RAW_FF_AR_REPORT_FILE_NOTES_DAILY (
    ENTITY_ID                   CHARACTER VARYING(255) ENCODE LZO
    , TRADING_BUSINESS_NAME     CHARACTER VARYING(1000) ENCODE LZO
    , NOTE                      CHARACTER VARYING(65000) ENCODE LZO
    , NOTEDATE                  CHARACTER VARYING(255) ENCODE LZO
    , NOTEAUTHOR                CHARACTER VARYING(255) ENCODE LZO
    , LOAD_DATE                 DATE ENCODE AZ64
    , LOAD_TS                   TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64
    , FILEPATH                  CHARACTER VARYING(255) ENCODE LZO
    , REPORT_DATE               DATE ENCODE AZ64
    , FLATFILE_RUN_ID           INTEGER ENCODE AZ64
    , FLATFILE_RUN_DETAIL_ID    INTEGER ENCODE AZ64
) DISTSTYLE AUTO;--Thu May 11 02:36:09 UTC 2023
CREATE TABLE IF NOT EXISTS DW_RAW.RAW_FF_AR_REPORT_FILE_NOTES_DAILY (
    ENTITY_ID                   CHARACTER VARYING(255) ENCODE LZO
    , TRADING_BUSINESS_NAME     CHARACTER VARYING(1000) ENCODE LZO
    , NOTE                      CHARACTER VARYING(65000) ENCODE LZO
    , NOTEDATE                  CHARACTER VARYING(255) ENCODE LZO
    , NOTEAUTHOR                CHARACTER VARYING(255) ENCODE LZO
    , LOAD_DATE                 DATE ENCODE AZ64
    , LOAD_TS                   TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64
    , FILEPATH                  CHARACTER VARYING(255) ENCODE LZO
    , REPORT_DATE               DATE ENCODE AZ64
    , FLATFILE_RUN_ID           INTEGER ENCODE AZ64
    , FLATFILE_RUN_DETAIL_ID    INTEGER ENCODE AZ64
) DISTSTYLE AUTO;