--Thu May 11 02:36:09 UTC 2023
CREATE TABLE IF NOT EXISTS DW_RAW.RAW_FF_INDUSTRY_CONSTANT_2020 (
    ENTITY_ID CHARACTER VARYING(255) ENCODE LZO,
    NAME CHARACTER VARYING(2000) ENCODE LZO,
    ABN BIGINT ENCODE AZ64,
    BUSINESSINDUSTRY INTEGER ENCODE AZ64,
    BUSINESS_INDUSTRY_NAME CHARACTER VARYING(2000) ENCODE LZO,
    LOAD_DATE DATE ENCODE AZ64,
    LOAD_TS TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64,
    FILEPATH CHARACTER VARYING(2000) ENCODE LZO,
    FLATFILE_RUN_ID INTEGER ENCODE AZ64,
    FLATFILE_RUN_DETAIL_ID INTEGER ENCODE AZ64
)
DISTSTYLE AUTO;