--Thu May 11 02:36:09 UTC 2023
CREATE TABLE IF NOT EXISTS DW_RAW.RAW_FF_MASTER_CLIENT_REPORT_DAILY (
    ENTITY_ID                   CHARACTER VARYING(255) ENCODE LZO
    , NAME                      CHARACTER VARYING(2000) ENCODE LZO
    , ABN                       BIGINT ENCODE AZ64
    , EMAIL                     CHARACTER VARYING(255) ENCODE LZO
    , EMAILTYPE                 CHARACTER VARYING(255) ENCODE LZO
    , INDUSTRYCLASS             CHARACTER VARYING(2000) ENCODE LZO
    , INDUSTRYGROUP             CHARACTER VARYING(2000) ENCODE LZO
    , INDUSTRYSUBDIVISION       CHARACTER VARYING(2000) ENCODE LZO
    , INDUSTRYDIVISION          CHARACTER VARYING(2000) ENCODE LZO
    , BUSINESSTYPE              CHARACTER VARYING(255) ENCODE LZO
    , APPLICATIONDATE           TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64
    , APPLICATIONMONTH          DATE ENCODE AZ64
    , APPLICATIONQUARTER        CHARACTER VARYING(255) ENCODE LZO
    , APPLICATIONYEAR           INTEGER ENCODE AZ64
    , APPROVEDATE               DATE ENCODE AZ64
    , APPROVEDBY                CHARACTER VARYING(255) ENCODE LZO
    , FACILITYAPPROVED          INTEGER ENCODE AZ64
    , FACILITYLIMIT             NUMERIC(24, 2) ENCODE AZ64
    , ENTITYTYPE                CHARACTER VARYING(255) ENCODE LZO
    , CHANGEDATE                TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64
    , AGEOFFILE                 DATE ENCODE AZ64
    , ABNREGDATE                CHARACTER VARYING(255) ENCODE LZO
    , SCORE                     INTEGER ENCODE AZ64
    , DEFAULTS                  INTEGER ENCODE AZ64
    , JUDGEMENTS                INTEGER ENCODE AZ64
    , WRITSNSUMMONS             INTEGER ENCODE AZ64
    , DISQUALIFIEDDIRECTORS     CHARACTER VARYING(255) ENCODE LZO
    , PETITIONS                 CHARACTER VARYING(255) ENCODE LZO
    , ENQUIRES                  INTEGER ENCODE AZ64
    , ENQUIRESIN12              INTEGER ENCODE AZ64
    , ENQUIRESBRACKET           INTEGER ENCODE AZ64
    , ENQUIRESIN12BRACKET       CHARACTER VARYING(255) ENCODE LZO
    , REFERRAL                  CHARACTER VARYING(2000) ENCODE LZO
    , AVERAGEDIRSCORE           NUMERIC(24, 1) ENCODE AZ64
    , AVERAGEDIRECTORBDAY       DATE ENCODE AZ64
    , AVERAGEDIRAGE             NUMERIC(24, 4) ENCODE AZ64
    , SCOREBUCKET               CHARACTER VARYING(255) ENCODE LZO
    , DIRECTORSCOREBUCKET       CHARACTER VARYING(255) ENCODE LZO
    , DIRECTORAGEBUCKET         CHARACTER VARYING(255) ENCODE LZO
    , FACILITYBUCKET            CHARACTER VARYING(255) ENCODE LZO
    , CLIENTCNT                 INTEGER ENCODE AZ64
    , EXCLUDE                   INTEGER ENCODE AZ64
    , EXCLUDEWITHNUTRANO        INTEGER ENCODE AZ64
    , TOTALDRAWDOWNAMT          NUMERIC(24, 2) ENCODE AZ64
    , TOTALOS                   NUMERIC(24, 2) ENCODE AZ64
    , TOTALPAYPLANOS            NUMERIC(24, 2) ENCODE AZ64
    , TOTALPAYPLANARREARSOS     NUMERIC(24, 2) ENCODE AZ64
    , TOTALARREARSOS            NUMERIC(24, 2) ENCODE AZ64
    , TOTAL90DAYSOS             NUMERIC(24, 2) ENCODE AZ64
    , TOTAL180DAYSOS            NUMERIC(24, 2) ENCODE AZ64
    , TOTALWRITEOFFOS           NUMERIC(24, 2) ENCODE AZ64
    , TOTALTRANSACTION          INTEGER ENCODE AZ64
    , TOTALOSTRANSACTION        INTEGER ENCODE AZ64
    , TOTALPAYPLANCNT           INTEGER ENCODE AZ64
    , TOTALARREARSTRANSACTION   INTEGER ENCODE AZ64
    , TOTAL90CNT                INTEGER ENCODE AZ64
    , TOTAL180CNT               INTEGER ENCODE AZ64
    , TOTALWRITEOFFCNT          INTEGER ENCODE AZ64
    , ISONPAYPLAN               INTEGER ENCODE AZ64
    , PAYPLANARREARS            INTEGER ENCODE AZ64
    , ISARREARSCLIENT           INTEGER ENCODE AZ64
    , FIRSTDRAWDATE             DATE ENCODE AZ64
    , FIRSTARREARSDATE          DATE ENCODE AZ64
    , EVERARREARS               INTEGER ENCODE AZ64
    , CUREDARREARS              INTEGER ENCODE AZ64
    , PASTCLIENT                INTEGER ENCODE AZ64
    , LASTACTIVEDATE            DATE ENCODE AZ64
    , DAYSACTIVE                INTEGER ENCODE AZ64
    , SOURCE                    CHARACTER VARYING(255) ENCODE LZO
    , SOURCEAPP                 CHARACTER VARYING(255) ENCODE LZO
    , FACILITYUTILISATIONRATE   NUMERIC(15, 9) ENCODE AZ64
    , DAYSTOFIRSTARREAR         INTEGER ENCODE AZ64
    , DAYSTOFIRSTDRAW           INTEGER ENCODE AZ64
    , DRAWDAYTOFIRSTARREAR      INTEGER ENCODE AZ64
    , MAXDUEDATE                INTEGER ENCODE AZ64
    , TOTALTRANSACTION1         INTEGER ENCODE AZ64
    , CLIENTSTATUS              CHARACTER VARYING(255) ENCODE LZO
    , APPROVESTATUS             CHARACTER VARYING(255) ENCODE LZO
    , DRAWNCLIENT               INTEGER ENCODE AZ64
    , BROKER                    CHARACTER VARYING(2000) ENCODE LZO
    , BROKERPOSTCODE            INTEGER ENCODE AZ64
    , BROKERMANAGER             CHARACTER VARYING(255) ENCODE LZO
    , FRANCHISEES               CHARACTER VARYING(255) ENCODE LZO
    , LASTDRAWDATE              DATE ENCODE AZ64
    , EXCLUDEDCLIENT            BOOLEAN ENCODE RAW
    , XLR8R_OS                  NUMERIC(24, 2) ENCODE AZ64
    , INSITE_OS                 NUMERIC(24, 2) ENCODE AZ64
    , SPARC_OS                  NUMERIC(24, 2) ENCODE AZ64
    , CASH_ADVANCE_OS           NUMERIC(24, 2) ENCODE AZ64
    , RECOVERY_PANDI_OS         NUMERIC(24, 2) ENCODE AZ64
    , RECOVERY_IONLY_OS         NUMERIC(24, 2) ENCODE AZ64
    , RMA_OS                    NUMERIC(24, 2) ENCODE AZ64
    , POS_OS                    NUMERIC(24, 2) ENCODE AZ64
    , OTHER_OS                  NUMERIC(24, 2) ENCODE AZ64
    , EFTCOUNT                  INTEGER ENCODE AZ64
    , LOAD_DATE                 DATE ENCODE AZ64
    , LOAD_TS                   TIMESTAMP WITHOUT TIME ZONE ENCODE AZ64
    , FILEPATH                  CHARACTER VARYING(255) ENCODE LZO
    , REPORT_DATE               DATE ENCODE AZ64
    , FLATFILE_RUN_ID           INTEGER ENCODE AZ64
    , FLATFILE_RUN_DETAIL_ID    INTEGER ENCODE AZ64
) DISTSTYLE AUTO;