name: test-workflow-1
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'redshift/dw-raw/*'
      - 'redshift/dw-risk/*'

permissions:
  contents: write
  pull-requests: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
