name: test-workflow-1
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'redshift/dw-raw/*'
      - 'redshift/dw-risk/*'

permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit report
        env:
          GH_TOKEN: "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"
        run: |
          for i in `find redshift/{dw-raw,dw-risk} -maxdepth 1 -type f`; do
            echo 'terraform apply'
            table_file="$(dirname $i)/tables/$(basename $i)"
            mkdir -p $(dirname $table_file)
            echo -e "\n-- $(date)" >> $table_file
            cat $i >> $table_file
            rm -f $i
            echo 'terraform state rm'
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true

          git branch -a
          git fetch
          git branch -a
          gh pr create -B dev -H main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
          git checkout dev
          git pull origin main --allow-unrelated-histories
          git push
