name: test-workflow-1
on: 
  push:
    branches: ['main']
    paths: ['redshift/*/tables-to-be-executed/*']

permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit report
        run: |
          for i in `find redshift/*/tables-to-be-executed -maxdepth 1 -type f`; do
            echo 'terraform apply'
            table_file="$(dirname $(dirname $i))/tables/$(basename $i)"
            echo --`date` >> $table_file
            cat $i >> $table_file
            >$i
            echo 'terraform state rm'
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git add .
          git commit -m "generated"
          git push
