name: alter-table-query
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['tables/alter/*']

permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit report
        run: |
          for i in `find tables/alter -maxdepth 1 -type f`; do 
            filename=$(basename -- "$i")
            extension="${filename##*.}"
            filename="${filename%.*}"
            echo "${filename}/${filename}_`date +"%Y%m%d_%H%M%S"`.${extension}"
            backup=${filename}/${filename}_`date +"%Y%m%d_%H%M%S"`.${extension}
            backup_dir=$(dirname -- "$i")
            mkdir -p $backup_dir
            ls -la */*/*
            mv $i $backup_dir/$backup
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git add .
          git commit -m "generated"
          git push
          
