name: test-workflow-1
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'redshift/dw-raw/*'
      - 'redshift/dw-risk/*'

permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Commit report
        run: |
          for i in `find redshift/{dw-raw,dw-risk} -maxdepth 1 -type f`; do
            echo 'terraform apply'
            table_file="$(dirname $i)/tables/$(basename $i)"
            mkdir -p $(dirname $table_file)
            echo -e "\n-- $(date)" >> $table_file
            cat $i >> $table_file
            rm -f $i
            echo 'terraform state rm'
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
          
          git add .
          git commit -m "generated"
          git push
          git branch -a
          git fetch
          git branch -a
          git checkout dev
          git pull origin main --allow-unrelated-histories
          git push
